### PR TITLE
make scroll smooth

### PR DESCRIPTION
**Pull request by him-raw99**
I did make the scroll smoother but the first time it scrolls all the way down to the testimonials section. This is because of the way you coded the carousel.

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
Hi @him-raw99 
can you please mention the issue you solved ;

**Comment by him-raw99** [comment]
sure,

currently if you'll click the subscribe button it'll scroll you to the testimonial section (not to the desired subscribe section) smoothly once but if you click the same button again it immediately pulls you to subscribe section ( right one but pulls abruptly ) 

but I have fixed that now 
>It'll smoothly scroll every time 
>I have set the scroll offset making it appear just at the right spot form top ( Not in the first go as described below )

although the issue that it'll scroll to testimonial section on the first go still persists because of the way you coded the testimonial section to change that issue you'll need to code testimonial section again.

**Comment by ayushgupta4002** [comment]
Thanks for explaining it in a brief way But I was just asking for you to please mention the issue number that you solved please do mention that too @him-raw99

**Comment by him-raw99** [comment]
sorry about for the confusion, I am new to opensource contribution so I am not certain but I think its 31st because it says issue #31  

Pasting the screen shot just to re-assure it. I appreciate your patience @ayushgupta4002 

image

**Comment by ayushgupta4002** [comment]
That's Completely fine @him-raw99, Thanks for your time and contribution !

**Pull request merged**
