### PR TITLE
Improved subscription form

### LINKED ISSUE #69: improvement: add responsiveness/css to components for better user experience
We might want to add good looking and responsive styles to components such as navbar matching with the theme of the project, for better user experience.

Example: upon hover, button looks like this,
Screenshot (81)

I would really like to contribute to this project, so please can you assign this issue to me. Thanks!
@ayushgupta4002

### PR DESCRIPTION
**Pull request by rishuraj1**
resolves #69 

Added styles and made necessary changes to make subscription form simpler and appealing. 

before changes:
Screenshot (92)

after changes: 
Screenshot (91)

Thank You!

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
@rishuraj1 we have changed our baseurl so can you please push the changes again !?

**Comment by rishuraj1** [comment]
@ayushgupta4002  made the necessary changes, can you verify ?

**Comment by ayushgupta4002** [comment]
thankyou @Adi-ty please review the UI

**Comment by Adi-ty** [comment]
Resolve conflicts @rishuraj1

**Comment by rishuraj1** [comment]
@Adi-ty  conflicts resolved. can you check if its okay? thanks!

**Comment by rishuraj1** [comment]
@Adi-ty  done!

**Review by Adi-ty — COMMENTED** [review]
Hey the form is not responsive it doesn't look good on small screens

**Comment by rishuraj1** [comment]
@ayushgupta4002  @Adi-ty  can you recheck? I made it responsive and resolved all conflicts.

**Pull request merged**
