### PR TITLE
Navbar and Landing page Update

### PR DESCRIPTION
**Pull request by amanjaiman1**
Hello @ayushgupta4002 i have updated the navbar and landing page with fonts , images UI ,
please merge it 

Next i will change footer in more professional UI version
Dhanyawad

### CODE REVIEW

**Comment by amanjaiman1** [comment]
Hey @ayushgupta4002 @rushabhpanbude @r3yc0n1c @isayakmondal please check my PR , i have changed the Navbar and landing page

**Comment by Divyansh3021** [comment]
Yeah it's good.

**Comment by amanjaiman1** [comment]
Please merge it then @ayushgupta4002 @Divyansh3021 bros ❤️

**Comment by amanjaiman1** [comment]
Thanks bro

**Pull request merged**
