### PR TITLE
Update: added css to certain components for better user experience.

### PR DESCRIPTION
**Pull request by rishuraj1**
Resolves : issue #69 

Added: 
 
1. css to the subscribe button at navbar, added scroll behaviour to the navbar.

Screenshot (81)

Screenshot (82)

2.  added styles to improve design in the about section.

Screenshot (84)

3.  updated the subscribe form to a simpler and modern looking form

Screenshot (85)

4.  added css to the mail to button at bottom

Screenshot (86)

PS: All changes are done according to the overall theme and coloring of the site.  Thank You!

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
@Adi-ty @Divyansh3021 please review

**Comment by Divyansh3021** [comment]
I liked the changes you did in Subscribe section, apart from that, i don't think the changes are more visually appealing than before. Thanks for your time. Highly appreciate your efforts.

**Comment by rishuraj1** [comment]
alright! @Divyansh3021  shall I create a fresh PR with just the changes required, as you mentioned.

**Comment by Divyansh3021** [comment]
Yeah sure

**Pull request closed without merging**
