### PR TITLE
Using HTML Entities for the apostrophe

### PR DESCRIPTION
**Pull request by jitendragangwar123**
I have used the HTML Entities for the apostrophe. Please review and merge it.

### CODE REVIEW

**Comment by Divyansh3021** [comment]
hey @jitendragangwar123 , please describe the issue that you have solved.

**Comment by jitendragangwar123** [comment]
Hey  @Divyansh3021, I have fixed the typo error you'll to you&#39;ll

**Comment by ayushgupta4002** [comment]
@jitendragangwar123 please resolve your merge conflicts

**Comment by jitendragangwar123** [comment]
Hii @ayushgupta4002 , I have resolved the conflict. Please check.

**Pull request merged**
