### PR TITLE
Redesigned the footer [GSSoC'23]

### LINKED ISSUE #174: The footer section can be improved. [GSSoC'23]
The footer section of the website is very basic and can be made more interesting. I can design a footer through figma and code in into the website.

Current footer section:
footer is very basic

Sample Footer:
sample footer design

### PR DESCRIPTION
**Pull request by 1Shubham7**
As I specified in the issue, I redesigned the footer entirely. Also the code in footer.js was very dirty, I cleaned it a little bit. The new footer looks like:

normal:
footerprbefore

hover:
footerprafter

Closes #174

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
@1Shubham7 Please change the footer color to #0d2f3f and try some different color on hovering instead of blue

**Comment by 1Shubham7** [comment]
ok @ayushgupta4002 . Just a minute.

**Comment by 1Shubham7** [comment]
@ayushgupta4002 . Done as you specified. Can you please merge the PR now?

**Comment by ayushgupta4002** [comment]
@1Shubham7 Your changes are still not visible Please make the background color for footer as #0d2f3f and try to change the color for hover effect

**Comment by 1Shubham7** [comment]
@ayushgupta4002 They are visible. See:
visible
I have made the changes 1 hour ago. Please check the files changed and reply me

**Comment by 1Shubham7** [comment]
@ayushgupta4002 I misunderstood what you said. Sorry for that. I think I have now made the appropriate changes. Please check them.

**Comment by ayushgupta4002** [comment]
thankyou for your contribution @1Shubham7 !

**Pull request merged**
