### PR TITLE
#44 Padding issue Resolved

### PR DESCRIPTION
**Pull request by piyushkhurana2019**
I had now solved the padding issue i.e. issue no. #44 that is used to came when seen in mobile view.

Before:- 

After:-

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
@tuhinaww @r3yc0n1c please review this issue and feel free to merge if it loos good to you !

**Comment by r3yc0n1c** [comment]
@piyushkhurana2019 looks good but remove the extra space/line feeds

**Comment by piyushkhurana2019** [comment]
> @piyushkhurana2019 looks good but remove the extra space/line feeds

will you please elaborate the issue ,you talking about

**Comment by r3yc0n1c** [comment]
> > @piyushkhurana2019 looks good but remove the extra space/line feeds
> 
> will you please elaborate the issue ,you talking about

check the CSS file you've modified... just remove the extra blank lines you've added

**Comment by piyushkhurana2019** [comment]
@r3yc0n1c kindly have a look now, i have removed the extra lines/spaces from the code

**Comment by r3yc0n1c** [comment]
> @r3yc0n1c kindly have a look now, i have removed the extra lines/spaces from the code

LGTM! Nice work!

@ayushgupta4002 @Divyansh3021 waiting for your reviews before merging

**Comment by ayushgupta4002** [comment]
please resolve the merge conflicts @piyushkhurana2019 
and do make sure to take a pull and push again !
regards

**Comment by ayushgupta4002** [comment]
@piyushkhurana2019 are you working on it?

**Pull request closed without merging**
