### PR TITLE
Added features and button is updated.

### PR DESCRIPTION
**Pull request by Rupantar-Borphukan**
Initially, it was like this --> 
original pic

Now, I have change the button (check after hovering). Then the Card is added to both left and right. Also, required field is added. 
Check it out --> 
Update-1
Update-2

### CODE REVIEW

**Comment by Divyansh3021** [comment]
Hey @Rupantar-Borphukan , I liked the changes you made in subscribe section UI. Can you correct the alignment of it in mobile view. Thanks

**Comment by Rupantar-Borphukan** [comment]
> Hey @Rupantar-Borphukan , I liked the changes you made in subscribe section UI. Can you correct the alignment of it in mobile view. Thanks

I have update the alignment of it Phone View. Please check it.

**Comment by ayushgupta4002** [comment]
that looks great @Rupantar-Borphukan , can you change the hover color to #0D2F3F ?

**Comment by Rupantar-Borphukan** [comment]
> that looks great @Rupantar-Borphukan , can you change the hover color to #0D2F3F ?

Hover color edited .
button-color edited

**Comment by ayushgupta4002** [comment]
thankyou @Rupantar-Borphukan for your contribution please mention the issue you solved in form of #issue.number

**Comment by ayushgupta4002** [comment]
@Rupantar-Borphukan Please solve your merge conficts

**Comment by Rupantar-Borphukan** [comment]
> @Rupantar-Borphukan Please solve your merge conficts

ok

**Comment by Rupantar-Borphukan** [comment]
> @Rupantar-Borphukan Please solve your merge conficts

Sorry, by mistake during trying to solve the conficts I have closed the issue. 
I have final push again by solving the conficts.

**Comment by Rupantar-Borphukan** [comment]
> thankyou @Rupantar-Borphukan for your contribution please mention the issue you solved in form of #issue.number

Issue is - Added features and button is updated. #73

**Pull request closed without merging**
