### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, @ayushgupta4002 I have successfully added the favicon to your project and also added a hover effect on buttons. Please review my pr and merge it. Thank you!
issue no #12

### CODE REVIEW

**Comment by ayushgupta4002** [comment]
hey @sumitkr2000 
this looks good, could you try making favicon white ?

**Comment by sumitkr2000** [comment]
@ayushgupta4002 bro but it will be not visible in the tab

**Comment by ayushgupta4002** [comment]
okay! @sumitkr2000 looks good then, please resolve your merge conflicts !
image

**Comment by ayushgupta4002** [comment]
@sumitkr2000 try making your forked repo up to date with main repo using sync and push it again after taking the pull!

**Comment by sumitkr2000** [comment]
@ayushgupta4002 it was too quick. I'll resolve it by tomorrow if u don't mind. Thank you.

**Comment by ayushgupta4002** [comment]
@sumitkr2000 that's completely fine !

**Comment by sumitkr2000** [comment]
@ayushgupta4002 now please check. I have resolved the merge conflict.

**Comment by ayushgupta4002** [comment]
Thank you @sumitkr2000 for your contribution !!

**Comment by sumitkr2000** [comment]
Thank you!

**Comment by sumitkr2000** [comment]
@ayushgupta4002 Please add level tag

**Pull request merged**
